# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-09 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DojoNinjasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
