# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='FirstApp.User')),
                ('users_who_like', models.ManyToManyField(related_name='liked_books', to='FirstApp.User')),
            ],
        ),
    ]
